version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=store
      - FLASK_ENV=development
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store