version: "2"
services:
  app:
    container_name: store-app
    image: app
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=store
      - FLASK_ENV=development
    volumes:
      - .:/app
  db:
    container_name: store-db
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store
  frontend:
    container_name: store-frontend
    build:
      context: frontend
    depends_on:
      - app
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  redis:
    container_name: store-redis
    image: redis:4.0.11
  download-worker:
    container_name: store-download-worker
    image: app
    command: python download_worker.py
    depends_on:
      - redis
    environment:
      - FLASK_APP=store
      - FLASK_ENV=development
    volumes:
      - .:/app
