"""empty message

Revision ID: 42344bf22343
Revises: dd25651d5f6b
Create Date: 2018-07-12 20:33:22.782885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42344bf22343'
down_revision = 'dd25651d5f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'rating')
    # ### end Alembic commands ###
